name: gome_intrinsic_height_memo
description: Efficient widget that caches intrinsic height after first layout.
version: 0.0.1
homepage: https://github.com/gumelartejasukma/gome_intrinsic_height_memo
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
